### ISSUE TITLE
Any chance of being able to set time/date of reminders?

### ISSUE THREAD

**Issue by greyhoundforty** [keith/reminders-cli#2]
I love this tool as it keeps me from having to jump out of the terminal but are there any plans for being able to set a due date?

**Comment by keith** [comment]
Thanks for the kind words!

I haven't thought about that too much yet since up to this point it hasn't been a feature of reminders I've used. But it totally makes sense to add.

Do you have any ideas on what the UI for this would be? It seems like that would be the most difficult part to get right, especially if you wanted the granularity.

Maybe we should check out some other tools that have similar uses cases, but if you have any ideas that would be great!

**Comment by greyhoundforty** [comment]
Hmm, my original thought was using the @ symbol followed by parenthesis:

`reminders add Inbox "Add this thing @(2016-07-29 14:00)" `

Honestly I am not sure it is really needed for a simple cli as I usually have the reminders app open on my phone so I just add the Due dates throughout the day.

**Comment by keith** [comment]
Hmm yea. I think the UI of this is the hardest part, otherwise it would be pretty easy to add. If we can come up with something pretty nice and typeable I'm happy to add it. If we can we should keep in mind that things can be repeating as well, which we may or may not also want to handle.

**Comment by gr-ae** [comment]
@keith Great idea for a cli-tool!
👍 due dates would be very useful

For UI how about...
`reminders add Inbox "this thing" (2016-07-29 14:00)`

It's GF-approved.  Though she doesn't understand why I don't just click on the Reminders.app [sigh]

P.S. Even better would be intelligent date parsing `(Tomorrow 14:00)`.

**Comment by lucasbento** [comment]
Added this feature here: https://github.com/lucasbento/reminders-cli

**Comment by keith** [comment]
If someone would like to submit a PR adding something like this I'm open to it!

**Comment by keith** [comment]
I implemented this feature here https://github.com/keith/reminders-cli/pull/20

**Comment by keith** [comment]
released here https://github.com/keith/reminders-cli/releases/tag/1.3.0
